### ISSUE TITLE
Soul-bound token

### ISSUE THREAD

**Issue by Jonas-Grill** [Jonas-Grill/mtp-blockchain#4]

**Comment by elianderlohr** [comment]
Schau dir auf jedenfall mal openzeppelin an. Die bieten eine sehr gute library um smart contracts und auch tokens zu erstellen. Ist vermutlich am besten deren erc20 zu nehmen und einfach die transfer funktion zu überschrieben und nur für unsere coinbase adresse freizugeben. https://docs.openzeppelin.com/contracts/4.x/wizard
